version: '3.8'

services:
  discordbot:
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    container_name: plexbot
    restart: unless-stopped
    depends_on:
      - lavalink
    env_file: 
      - ../.env
    networks:
      - lavalink

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:0326284-alpine
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
      - LAVALINK_ADDRESS=0.0.0.0
      - LAVALINK_PASSWORD=youshallnotpass
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    expose:
      - 2333
    ports:
      - "2333:2333"

networks:
  lavalink:
    name: lavalink
